---
# Source: yorisoi-local/charts/yorisoi-stack/templates/frontend-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.js: |
    window.ENV = {
      API_URL: "/admin"
    };
---
# Source: yorisoi-local/charts/yorisoi-stack/templates/backend-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 9000       # Port nội bộ Service
      targetPort: 80   # Port của Container (Nginx)
---
# Source: yorisoi-local/charts/yorisoi-stack/templates/frontend-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
# Source: yorisoi-local/charts/yorisoi-stack/templates/mysql-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
# Source: yorisoi-local/charts/yorisoi-stack/templates/backend-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "harbor.local.thongdev.site/lab-final/backend:v1.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # Nginx trong container mở cổng 80
          env:
            # 1. Config từ values.yaml
            - name: APP_ENV
              value: "local"
            - name: APP_DEBUG
              value: "true"
            - name: APP_URL
              value: "http://dr.thongdev.site"
            - name: DB_HOST
              value: "mysql-svc"
            
            # 2. Secret từ K8s (Password, Key)
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: 
                  key: APP_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: 
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: 
                  key: DB_USERNAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: 
                  key: JWT_SECRET
---
# Source: yorisoi-local/charts/yorisoi-stack/templates/frontend-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "harbor.local.thongdev.site/lab-final/frontend:v1.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            # Ghi đè file config.js giả lập vào container
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config
---
# Source: yorisoi-local/charts/yorisoi-stack/templates/mysql-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-svc
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: 
              key: DB_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: 
              key: DB_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: 
              key: DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: 
              key: DB_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
# Source: yorisoi-local/charts/yorisoi-stack/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yorisoi-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: dr.thongdev.site
    http:
      paths:
      # 1. Backend nhận /admin (Theo yêu cầu của bạn)
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port: { number: 9000 }
      # 2. Backend nhận /api (Chuẩn Laravel)
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port: { number: 9000 }
      # 3. Frontend nhận phần còn lại
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port: { number: 80 }
---
# Source: yorisoi-local/charts/yorisoi-stack/templates/migration-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-migrate-1
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: "harbor.local.thongdev.site/lab-final/backend:v1.0.0"
        command: ["php", "artisan", "migrate", "--force"]
        envFrom:
          - secretRef:
              name: 
        env:
          - name: DB_HOST
            value: "mysql-svc"
